# -*- coding: utf-8 -*-
"""memes.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wvMHk3xLuZ-5X4vQz9qTdOfB71Etv08S
"""

import gradio as gr
import requests
from PIL import Image
from io import BytesIO

def get_meme():
    response = requests.get("https://meme-api.com/gimme/wholesomememes")
    data = response.json()
    url = data["url"]
    img_response = requests.get(url)
    img = Image.open(BytesIO(img_response.content))
    return img

iface = gr.Interface(fn=get_meme, 
                     inputs=None, 
                     outputs=gr.outputs.Image(type="pil"), 
                     title="Random Meme Generator",
                     description="Click the button below to generate a random meme.")

iface.launch(share=True)